services:
  tugtainer:
    image: quenary/tugtainer:latest
    container_name: tugtainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /storage/data/tugtainer:/tugtainer
    environment:
      - TZ=Asia/Kuala_Lumpur
      - HOSTNAME=tugtainer.alimunee.com
      - LOG_LEVEL=warning
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tugtainer.rule=Host(`tugtainer.alimunee.com`)"
      - "traefik.http.services.tugtainer.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/public/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  proxy:
    external: true
